poped.db <- create.poped.database(ff_file="ff.1.comp.oral.md.imax",
                                  fError_file="feps.1.comp.oral.md.imax",
                                  groupsize=20,
                                  m=2,
                                  sigma=sigma_vals,
                                  bpop=bpop_vals,  
                                  notfixed_bpop=notfixed_bpop,
                                  notfixed_sigma=notfixed_sigma,
                                  d=d_vals, 
                                  xt=c( 1,2,8,240,245,1,2,8,240,245),
                                  minxt=c(0,0,0,240,240,0,0,0,240,240),
                                  maxxt=c(10,10,10,248,248,10,10,10,248,248),
                                  model_switch=c(1,1,1,1,1,2,2,2,2,2),
                                  a=rbind(20,40),
                                  bUseGrouped_xt=1,
                                  maxa=200,
                                  mina=0)  


poped.db.1 <- create.poped.database(list(),
                                    ff_file="ff",
                                    fError_file="feps",
                                    groupsize=20,
                                    m=2,
                                    sigma=sigma_vals,
                                    bpop=bpop_vals,  
                                    notfixed_bpop=notfixed_bpop,
                                    notfixed_sigma=notfixed_sigma,
                                    d=d_vals, 
                                    xt=c( 1,2,8,240,245,1,2,8,240,245),
                                    minxt=c(0,0,0,240,240,0,0,0,240,240),
                                    maxxt=c(10,10,10,248,248,10,10,10,248,248),
                                    model_switch=c(1,1,1,1,1,2,2,2,2,2),
                                    a=rbind(20,40),
                                    bUseGrouped_xt=1,
                                    maxa=200,
                                    mina=0)  

# reducing design space and adding ourzero.
poped.db.2 <- create.poped.database(list(),
                                    ff_file="ff",
                                    fError_file="feps",
                                    groupsize=20,
                                    m=2,
                                    sigma=sigma_vals,
                                    bpop=bpop_vals,  
                                    notfixed_bpop=notfixed_bpop,
                                    notfixed_sigma=notfixed_sigma,
                                    d=d_vals, 
                                    xt=c( 1,2,8,240,240,1,2,8,240,240),
                                    minxt=c(0,0,0,240,240,0,0,0,240,240),
                                    maxxt=c(10,10,10,248,248,10,10,10,248,248),
                                    G_xt=c(1,2,3,4,5,1,2,3,4,5),
                                    model_switch=c(1,1,1,1,1,2,2,2,2,2),
                                    a=rbind(20,40),
                                    bUseGrouped_xt=1,
                                    ourzero=0,
                                    maxa=200,
                                    mina=0)  

# adding a placebo group
poped.db.3 <- create.poped.database(list(),
                                    ff_file="ff",
                                    fError_file="feps",
                                    groupsize=20,
                                    m=3,
                                    sigma=sigma_vals,
                                    bpop=bpop_vals,  
                                    notfixed_bpop=notfixed_bpop,
                                    notfixed_sigma=notfixed_sigma,
                                    d=d_vals, 
                                    xt=c( 1,2,8,240,240,1,2,8,240,240),
                                    minxt=c(0,0,0,240,240,0,0,0,240,240),
                                    maxxt=c(10,10,10,248,248,10,10,10,248,248),
                                    G_xt=c(1,2,3,4,5,1,2,3,4,5),
                                    model_switch=c(1,1,1,1,1,2,2,2,2,2),
                                    a=rbind(20,40,0),
                                    bUseGrouped_xt=1,
                                    ourzero=0,
                                    maxa=200,
                                    mina=0)  

# Adding 10% Uncertainty to IC50 parameter
bpop_vals_ed <- cbind(zeros(7,1),bpop_vals,zeros(7,1)) 
bpop_vals_ed["IC50",1] <- 1
bpop_vals_ed["IC50",3] <- (bpop_vals_ed["IC50",2]*0.1)^2
bpop_vals_ed

poped.db.4 <- create.poped.database(list(),
                                    ff_file="ff",
                                    fError_file="feps",
                                    groupsize=20,
                                    m=3,
                                    sigma=sigma_vals,
                                    bpop=bpop_vals_ed,  
                                    notfixed_bpop=notfixed_bpop,
                                    notfixed_sigma=notfixed_sigma,
                                    d=d_vals, 
                                    xt=c( 1,2,8,240,240,1,2,8,240,240),
                                    minxt=c(0,0,0,240,240,0,0,0,240,240),
                                    maxxt=c(10,10,10,248,248,10,10,10,248,248),
                                    G_xt=c(1,2,3,4,5,1,2,3,4,5),
                                    model_switch=c(1,1,1,1,1,2,2,2,2,2),
                                    a=rbind(20,40,0),
                                    bUseGrouped_xt=1,
                                    ourzero=0,
                                    ED_samp_size=20,
                                    maxa=200,
                                    mina=0)


